package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"

	resp "github.com/vano2903/ipaas/responser"
)

//! still under development
//new database handler, let the user create a new database given the default db name (can be null)
//credentials will be autogenerated
//the body should contain:
//1) db name
//2) db type (mysql, mariadb, mongodb)
//! 3) (not implemented) db version (can be null which will mean the latest version)
func (h Handler) NewDBHandler(w http.ResponseWriter, r *http.Request) {
	//connect to the db
	conn, err := connectToDB()
	if err != nil {
		resp.Errorf(w, http.StatusInternalServerError, "error connecting to the database: %v", err.Error())
		return
	}
	defer conn.Close()

	//get the student from the cookies
	student, err := h.util.GetUserFromCookie(r, conn)
	if err != nil {
		resp.Errorf(w, http.StatusInternalServerError, "error getting the user from cookies: %v", err.Error())
		return
	}

	//read post body
	var dbPost dbPost
	err = json.NewDecoder(r.Body).Decode(&dbPost)
	if err != nil {
		resp.Errorf(w, http.StatusBadRequest, "error decoding the json: %v", err.Error())
		return
	}

	//generate env variables for the container
	password := generateRandomString(16)
	var env []string
	switch dbPost.DbType {
	case "mysql", "mariadb":
		//root password
		env = []string{
			"MYSQL_ROOT_PASSWORD=" + password,
		}
		//set a database if it's not empty
		if dbPost.DbName != "" {
			env = append(env, "MYSQL_DATABASE="+dbPost.DbName)
		}
	case "mongodb":
		//root password
		env = []string{
			"MONGO_INITDB_ROOT_USERNAME=" + "root",
			"MONGO_INITDB_ROOT_PASSWORD=" + password,
		}
		//set a database if it's not empty
		//!apparently this part doesn't work, the user can create the db on it's own though
		if dbPost.DbName != "" {
			env = append(env, "MONGO_INITDB_DATABASE="+dbPost.DbName)
		}
	default:
		resp.Error(w, http.StatusBadRequest, "Invalid db type, must be mysql, mariadb or mongodb")
		return
	}

	//create the database container
	id, err := h.cc.CreateNewDB(h.cc.dbContainersConfigs[dbPost.DbType], env)
	if err != nil {
		resp.Errorf(w, http.StatusInternalServerError, "error creating a new database: %v", err.Error())
		return
	}

	//get the external port
	port, err := h.cc.GetContainerExternalPort(id, h.cc.dbContainersConfigs[dbPost.DbType].port)
	if err != nil {
		resp.Errorf(w, http.StatusInternalServerError, "error getting the external port: %v", err.Error())
		return
	}

	//add a new database application created by the student (student id)
	insertApplicationQuery := `
	INSERT INTO applications (containerID, status, studentID, type, name, description, port, externalPort) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	`

	//exec the query, the status will be up and type database, the name will follow the nomenclature of <studentID>:<dbType>/<dbName>
	_, err = conn.Exec(insertApplicationQuery, id, "up", student.ID, "database", fmt.Sprintf("%d:%s/%s", student.ID, dbPost.DbType, dbPost.DbName), "", h.cc.dbContainersConfigs[dbPost.DbType].port, port)
	if err != nil {
		resp.Errorf(w, http.StatusInternalServerError, "unable to link the application to the user: %v", err.Error())
		return
	}

	json := map[string]interface{}{
		"important": "the password is for root user of the server",
		"user":      "root",
		"port":      port,
		"pass":      password,
	}
	if dbPost.DbType == "mongodb" {
		json["uri"] = fmt.Sprintf("mongodb://root:%s@%s:%s", password, os.Getenv("IP"), port)
	}
	resp.SuccessParse(w, http.StatusOK, "New DB created", json)
}

//! under development, not implementing it now
//! if you want to export the database use an external tool
// /user/
// func (h Handler) ExportDBHandler(w http.ResponseWriter, r *http.Request) {
// 	vars := mux.Vars(r)
// 	containerID := vars["containerID"]

// 	//read the post body
// 	var dbPost dbPost
// 	err := json.NewDecoder(r.Body).Decode(&dbPost)
// 	if err != nil {
// 		resp.Errorf(w, http.StatusBadRequest, "error decoding the json: %v", err.Error())
// 		return
// 	}

// 	//connect to the db
// 	conn, err := connectToDB()
// 	if err != nil {
// 		resp.Errorf(w, http.StatusInternalServerError, "error connecting to the database: %v", err.Error())
// 		return
// 	}
// 	defer conn.Close()
// 	//get the student from the cookies
// 	student, err := h.util.GetUserFromCookie(r, conn)
// 	if err != nil {
// 		resp.Errorf(w, http.StatusInternalServerError, "error getting the user from cookies: %v", err.Error())
// 		return
// 	}

// 	//check if the user owns the db container
// 	var app Application
// 	err = conn.QueryRow(`SELECT * FROM applications WHERE type='database' AND studentID = ? AND containerID = ?`, student.ID, containerID).Scan(&app.ID, &app.ContainerID, &app.Status, &app.StudentID, &app.Type, &app.Name, &app.Description)
// 	if err != nil {
// 		if err == sql.ErrNoRows {
// 			resp.Error(w, http.StatusBadRequest, "application not found, check if the container id is correct and make sure you own this database")
// 		}
// 	}

// 	dbPost.DbType = strings.Split(strings.Split(app.Name, ":")[1], "/")[0]

// }
