version: "3.9"

services:
    # application-service:
    #   container_name: application-service-ipaas
    #   restart: "no"
    #   build:
    #     context: ./applications-service
    #     dockerfile: Dockerfile
    #   networks:
    #     - "ipaas"
    db:
      image: mongo:5.0
      restart: always
      container_name: 'mongo-ipaas'
      environment:
        MONGO_INITDB_ROOT_USERNAME: vano
        MONGO_INITDB_ROOT_PASSWORD: vanovano
        MONGO_INITDB_DATABASE: ipaas
      ports:
        - "27018:27017"
      volumes:
        - ./ipaas-db-dump/data:/data/db
      networks:
        - "ipaas"
    rabbitmq:
      restart: always
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq-ipaas'
      environment:
        - RABBITMQ_DEFAULT_USER=vano
        - RABBITMQ_DEFAULT_PASS=adminvano
      ports:
        - "5671:5672"
        - "15671:15672"
      volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      networks:
        - ipaas
    jaeger:
      container_name: jaeger-ipaas
      image: jaegertracing/all-in-one:latest
      networks:
      - ipaas
      ports:
      - "16686:16686"
      - "14269:14269"

volumes:
  db:
  rabbitmq:

networks:
  ipaas:
    name: "ipaas-network"