version: "3.9"

services:
    # go:
    #   # container_name: go
    #   image: go
    #   restart: always
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   links:
    #     - db
    #   ports:
    #     - "80:8080"
    #   networks:
    #     - "ipaas"
    db:
      image: mongo:5.0
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: vano
        MONGO_INITDB_ROOT_PASSWORD: vanovano
      ports:
        - 27017:27017
      volumes:
        - ~/ipaas-db-dump:/data/db
      networks:
        - "ipaas"
volumes:
  db:

networks:
  ipaas: