CREATE DATABASE IF NOT EXISTS ipaas;

USE ipaas;

CREATE TABLE IF NOT EXISTS `states` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `state` char(24) NOT NULL,
    `issDate` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;