FROM golang:1.18-alpine as build
RUN apk add --no-cache git

WORKDIR /src 

COPY .env /src/
COPY go.sum /src/
COPY go.mod /src/
RUN go mod download

COPY *.go /src/

RUN go build -o app
RUN cat .env

FROM alpine:3.12

RUN mkdir -p /app
COPY --from=build /src/ /app/
RUN cat /app/.env
CMD ["./app/app"]