package main

type Student struct {
	ID       int    `bson:"userID" json:"matricola"` //id of the student (teachers will use the same, but it's 6 digit long instead of 5)
	Name     string `bson:"name" json:"nome"`        //name of the student
	LastName string `bson:"lastName" json:"cognome"` //last name of the student
	Email    string `bson:"email" json:"email"`      //email of the student
	Pfp      string `bson:"pfp" json:"pfp"`          //profile picture of the student (autogenerated)
}
